import Head from "next/head";
import { AiFillLinkedin, AiFillGithub, AiFillFacebook } from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { BsFillSunFill } from "react-icons/bs";
import { IoMdDownload } from "react-icons/io";
import { useState } from "react";
import avatar from "../public/avatar.png";
import code from "../public/code.png";
import design from "../public/design.png";
import consulting from "../public/consulting.png";
import Image from "next/image";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
export default function Home() {
  const [darkMode, setDarkMode] = useState(true);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Md. Samin Irtiza</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-8 flex justify-between dark:text-white">
            <h1 className="font-burtons text-xl">S. Irtiza</h1>
            <ul className="flex items-center">
              <li>
                {darkMode ? (
                  <BsFillSunFill
                    onClick={() => setDarkMode(!darkMode)}
                    className=" cursor-pointer text-2xl"
                  />
                ) : (
                  <BsFillMoonStarsFill
                    onClick={() => setDarkMode(!darkMode)}
                    className=" cursor-pointer text-2xl"
                  />
                )}
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8 flex"
                  href="/Md._Samin_Irtiza_resume.pdf"
                >
                  <IoMdDownload className="text-2xl justify-between mr-2"/>
                  Resume / CV
                </a>
              </li>
            </ul>
          </nav>
          <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-8 md:h-96 md:w-96">
            <Image src={avatar} layout="fill" objectFit="cover" />
          </div>
          <div className="text-center p-10 py-10">
            <h2 className="mb-8 font-barcelony text-5xl py-2 text-teal-800 font-bold dark:text-teal-400 md:text-6xl">
              Samin Irtiza
            </h2>
            <h3 className="font-burtons text-2xl py-2 dark:text-white md:text-3xl">
              Developer and AI artist.
            </h3>
            <p className="font-poppins text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
              Freelancer providing services for programming and design content
              needs. Join me down below and let&apos;s get cracking!
            </p>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
              <a href="https://www.linkedin.com/in/samin-irtiza/">
                <AiFillLinkedin />
              </a>
              {/* <a href="https://www.facebook.com/saminirtiza.arnob/">
                <AiFillFacebook />
              </a> */}
              <a href="https://www.github.com/samin-irtiza/">
                <AiFillGithub />
              </a>
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Services I offer</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              I offer from a wide range of services, including brand design,
              programming and teaching.
            </p>
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-black shadow-md p-10 rounded-xl my-10  dark:bg-amber-400 flex-1">
              <Image src={design} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2  ">
                Beautiful Designs
              </h3>
              <p className="py-2">
                Creating elegant designs suited for your needs following core
                design theory.
              </p>
              <h4 className="py-4 font-semibold text-violet-900">Design Tools I Use</h4>
              <p className="text-gray-800 py-1">GIMP</p>
              <p className="text-gray-800 py-1">Inkscape</p>
              <p className="text-gray-800 py-1">Figma</p>
              <p className="text-gray-800 py-1">Stable Diffusion</p>
            </div>
            <div className="text-center shadow-black shadow-md p-10 rounded-xl my-10 dark:bg-amber-400 flex-1">
              <Image src={code} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2 ">
                Code your dream project
              </h3>
              <p className="py-2">
                Do you have an idea for your next great website? Let&apos;s make it a
                reality.
              </p>
              <h4 className="py-4 font-semibold text-violet-900">Coding Tools I Use</h4>
              <p className="text-gray-800 py-1">Django</p>
              <p className="text-gray-800 py-1">React</p>
              <p className="text-gray-800 py-1">NextJs</p>
              <p className="text-gray-800 py-1">NodeJs</p>
            </div>
            <div className="text-center shadow-black shadow-md p-10 rounded-xl my-10 dark:bg-amber-400 flex-1">
              <Image src={consulting} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2 ">Consulting</h3>
              <p className="py-2">
                Are you interested in feedback for your current project? I can
                give you tips and tricks to level it up.
              </p>
              <h4 className="py-4 font-semibold text-violet-900">Contact me</h4>
              <a
                className=" text-white font-semibold bg-lime-800 px-4 rounded-md py-1 border-lime-700"
                href="https://www.fiverr.com/share/kr0VlQ"
              >
                Fiverr
              </a>
            </div>
          </div>
        </section>
        <section className="py-10">
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Portofolio</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
                Here are some of my works
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap ">
            <div className="basis-1/3 flex-1 rounded-lg shadow-black shadow-lg transform transition duration-200 hover:scale-110">
              <a href="https://eternull404.pythonanywhere.com/" target="_blank">
              <Image
                className="rounded-lg object-cover "
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web1}
                />
              </a>
            </div>
            <div className="basis-1/3 flex-1 rounded-lg shadow-black shadow-lg transform transition duration-200 hover:scale-110">
              <a href="#" target="_top">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web2}
                />
              </a>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
